name: CI
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.3
      - uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
      
      - name: Lint
        run: pnpm run workflow:check
      
      - name: Build
        run: pnpm run build
      
      - name: Test
        run: pnpm run test